
// Tipos de dados PRIMITIVOS
//Number, String, Boolean, Undefined, Null

let numero = 10;
let valor = 20.40; //float

//String
let nome = "FULANO"

// Bolean // Verdadeiro (true) ou Falso (false)
let freteGratis = true;

/* Undefined: 
 Representa a ausência de valor. Geralmente, 
 e o valor padrão para variaveis recém - declarado. */
let desconto;

//Null - Representa a ausência intencional de qualquer valor ou
//objeto.

let total = null;

