let nota1 = 10;
let nota2 = 6;
let penalizacao = 3;

let media = (nota1 + nota2 - penalizacao) / 2;

let resultado = "A sua média é:" + media;


//console.log ((nota1 + nota2) / 2)
// var e let são variaveis

//console.log(resultado)

let nome = "Isabella";
let sobrenome ="Corrêa";
let nomeCompleto = nome + " " + sobrenome;

//console.log(nomeCompleto)


//Celsius > Fahrenheit

//Multiplicamos a temperatura em C por 1,8 e somamos 32 ao resultado.

let temperatura = 25;
let calculo = temperatura * 1.8 + 32;
console.log(calculo);

